### ISSUE TITLE
Slow boot time in Monterey version

### ISSUE THREAD

**Issue by nhdanh** [JhonsonT/ROG-B460G-10400-UHD630-OPENCORE#3]
Thank for your EFI folder. I use same spec with you. 
So when I use Bigsur. Boot time very fast. Only 20s to complete boot. 
 I update to Montery from Software Update. Now my boot time 2 minute. 

Are you get slow boot time same me ? Thank for reply

**Comment by JhonsonT** [comment]
Thanks for your question, when I use macOS Monterey, my boot time takes 35 seconds, which is a bit slower than when I used macOS Bigsur before. The bios settings of my motherboard, the opencore boot settings, and the boot time video are placed in the BootTime folder of the git repository. You can refer to it.

**Comment by nhdanh** [comment]
Thank for your reply. I config the boot setting and using same folder EFI with you. Still get slow boot. I think I should reinstall macos ^^.

And I have question. I using hackintool. In tab USB. A PXSX Name show ???. Not show name controller. Is it normal ? How to fix to show the name controller. Thank you again ^^
<img width="666" alt="Screen Shot 2021-10-30 at 09 40 55" src="https://user-images.githubusercontent.com/32826936/139517583-4d7438a6-34f6-4646-b51a-fa1ecb6816cc.png">
.

**Comment by JhonsonT** [comment]
My hackintool also shows this, and no fix is found, but it does not affect the use

**Comment by nhdanh** [comment]
Thank for support. I will reinstall to fix slow boot time ^^
