### ISSUE TITLE
睡眠自动重启

### ISSUE THREAD

**Issue by yuanyaxing** [JhonsonT/ROG-B460G-10400-UHD630-OPENCORE#4]
发现一个问题，电脑每周日都会自动重启下
平时用完直接睡眠，第二天再打开，还是跟睡眠之前一样
但是周日那天，一天都没碰电脑，周一过来就跟重启完之后一样，软件都关了
想问下又遇到这种情况吗，或者知道怎么解不
（同款配置）

**Comment by JhonsonT** [comment]
没有遇到哎。。。每周日自动重启，这么规律的吗

**Comment by yuanyaxing** [comment]
> 没有遇到你。。。每周日自动重启，科学规律的吗？

是的，连续三四周都是这样了

**Comment by JhonsonT** [comment]
这个我恐怕没法帮你，没有遇到过

**Comment by yuanyaxing** [comment]
> 这个我恐怕没法帮你，没有遇到过

好的，还是谢谢你

**Comment by JhonsonT** [comment]
没事，我也没帮到啥^_^
