### ISSUE TITLE
请教一下加独显(rx6600xt)

### ISSUE THREAD

**Issue by littlesierra** [JhonsonT/ROG-B460G-10400-UHD630-OPENCORE#5]
请问，用核显正常，加上RX6600XT，显示器接独显DP接口，OC引导到苹果Logo就黑屏了，需要改什么配置吗？

**Comment by JhonsonT** [comment]
缓冲帧换了嘛

**Comment by JhonsonT** [comment]
核显缓冲帧换了嘛，换成加速缓冲帧，6600xt的话是在12.1系统以后加入内置驱动的吧，你的系统版本对嘛

**Comment by littlesierra** [comment]
请问，缓冲帧怎么换呀？我只加了weg的agdpmod=pikera参数，系统是12.3.1

**Comment by JhonsonT** [comment]
> 请问，缓冲帧怎么换呀？我只加了weg的agdpmod=pikera参数，系统是12.3.1
看下文档
https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#deviceproperties

**Comment by littlesierra** [comment]
感谢指点，我这几天有空了研究一下
